#!/usr/bin/env node
/**
 * Builds one self-contained bundle per dealers/<name>.json, plus a stable
 * loader per dealer.
 *
 *   node build.js            bundles only
 *   node build.js v1.2.0     bundles + loaders pointing at that tag
 *
 * Two-file deploy model:
 *
 *   dist/<name>.js         the widget. Pinned to a tag, SRI-hashed, immutable.
 *   dist/loader/<name>.js  ~10 lines. Served from @main so its URL never
 *                          changes; injects the pinned bundle with integrity
 *                          applied in JS (SRI works on dynamic scripts).
 *
 * The dealer pastes the loader URL once and never touches it again. Deploying
 * means rebuilding the loader against a new tag, pushing main, and purging the
 * loader URL — no dealer-side edit, while the payload stays tamper-proof.
 *
 * The bundle is standalone rather than fetched in pieces so it can carry its
 * own SRI hash. The loader itself carries no SRI — nothing could verify it,
 * which is the unavoidable cost of a mutable URL. Keep it tiny and boring.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const REPO = 'AutoDroids-ai/autodroids-chat-widget';
const ENGINE = path.join(__dirname, 'src', 'engine.js');
const MARKER = '/*__DEALER__*/{}';
const tag = process.argv[2] || '';

const engine = fs.readFileSync(ENGINE, 'utf8');
if (!engine.includes(MARKER)) {
  console.error('build: marker ' + MARKER + ' not found in src/engine.js');
  process.exit(1);
}
if (tag && !/^(v[0-9]+[.][0-9]+[.][0-9]+|[0-9a-f]{7,40})$/.test(tag)) {
  console.error('build: ref must be a v1.2.3 tag or a commit sha, got ' + tag);
  process.exit(1);
}

fs.mkdirSync(path.join(__dirname, 'dist', 'loader'), { recursive: true });

const dealers = fs.readdirSync(path.join(__dirname, 'dealers')).filter(f => f.endsWith('.json'));
let failed = 0;

for (const file of dealers) {
  const name = path.basename(file, '.json');
  const cfg = JSON.parse(fs.readFileSync(path.join(__dirname, 'dealers', file), 'utf8'));

  if (!cfg.closebotSource) {
    console.error(`build: ${file} has no closebotSource`);
    failed++;
    continue;
  }
  // Tags feed CloseBot routing rules; a duplicate silently misroutes a rooftop.
  const tags = (cfg.locations || []).map(l => l.tag);
  if (new Set(tags).size !== tags.length) {
    console.error(`build: ${file} has duplicate location tags`);
    failed++;
    continue;
  }

  // Strip _-prefixed doc keys so they never ship to the browser.
  const shipped = Object.fromEntries(Object.entries(cfg).filter(([k]) => !k.startsWith('_')));

  const banner = `/*! AutoDroids Chat Widget — ${name} — built from dealers/${file}. Do not edit. */\n`;
  const out = banner + engine.replace(MARKER, JSON.stringify(shipped, null, 2));

  fs.writeFileSync(path.join(__dirname, 'dist', name + '.js'), out, 'utf8'); // LF pinned by .gitattributes
  const hash = crypto.createHash('sha384').update(Buffer.from(out, 'utf8')).digest('base64');
  console.log(`built dist/${name}.js  (${(cfg.locations || []).length} locations, source=${cfg.closebotSource})`);

  if (!tag) continue;

  // The manifest is the only thing that has to be fresh. It is fetched with
  // GitHub raw, not jsDelivr: jsDelivr's @main branch snapshot goes stale for up
  // to 12h (s-maxage=43200) and purging does not clear it -- observed serving a
  // superseded manifest even with a cache-busting query. Raw sets max-age=300, so
  // a deploy lands within 5 minutes. The baked-in fallback keeps chat working if
  // the manifest request fails or GitHub rate-limits.
  const manifest = { src: `https://cdn.jsdelivr.net/gh/${REPO}@${tag}/dist/${name}.js`, integrity: `sha384-${hash}` };
  fs.writeFileSync(path.join(__dirname, 'dist', 'loader', name + '.json'), JSON.stringify(manifest, null, 2) + String.fromCharCode(10), 'utf8');

  const loader =
`/*! AutoDroids Chat Widget loader — ${name}. Generated by build.js; do not edit.
 * Stable URL: the dealer pastes this once and never touches it again.
 * Reads dist/loader/${name}.json from GitHub raw (max-age=300), so a deploy
 * lands within ~5 minutes with no dealer-side edit. jsDelivr is not used for the
 * manifest: its @main snapshot goes stale for up to 12h and purging does not
 * clear it. The pinned bundle it points to is still served by jsDelivr. */
(function () {
  var FALLBACK = { src: '${manifest.src}', integrity: '${manifest.integrity}' };
  var MANIFEST = 'https://raw.githubusercontent.com/${REPO}/main/dist/loader/${name}.json';
  var done = false;
  function inject(m) {
    if (done) return;
    done = true;
    if (!m || !m.src || !m.integrity) m = FALLBACK;
    var s = document.createElement('script');
    s.src = m.src;
    s.integrity = m.integrity;
    s.crossOrigin = 'anonymous';
    s.defer = true;
    document.head.appendChild(s);
  }
  try {
    fetch(MANIFEST)
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(inject)
      .catch(function () { inject(FALLBACK); });
  } catch (e) { inject(FALLBACK); }
})();
`;
  fs.writeFileSync(path.join(__dirname, 'dist', 'loader', name + '.js'), loader, 'utf8');
  console.log(`      loader -> ${tag}  sha384-${hash.slice(0, 12)}...`);
}

process.exit(failed ? 1 : 0);
